[project]
name = "chess-move-explainer"
version = "0.1.0"
description = "A tool that suggests and explains chess moves for beginners"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-chess",
    "stockfish",
    "rich",
]
